goog.provide('waveney.layers.links');
waveney.layers.links.description__GT_url = cljs.core.PersistentHashMap.fromArrays(["defra - water level gauges (interactive map)","national parks uk - folklore of the broads","the south folk of the east angles (anglo-saxon history)","river waveney trust (conservation and restoration)","visit waveney valley (tourism information)","east anglian traditional music - waveney songs community project","visit waveney valley - trail maps","waveney & little ouse recovery project (restoration)","broads authority - river waveney depth and navigation notes","suffolk real ale pubs (interactive map)"],["https://lfw-prdg.aws.defra.cloud/river-and-sea-levels/target-area/054wacdv3b?group=rainfall&v=map-live&lyr=ri,gr,mv&ext=0.726202,51.976492,1.825489,53.258732&fid=stations.9620","https://www.nationalparks.uk/2024/09/30/discover-folklore-of-the-broads/","https://www.wilcuma.org.uk/east-anglia/the-south-folk-of-the-east-angles/","https://www.riverwaveneytrust.org/","https://visitwaveneyvalley.co.uk/","https://www.eatmt.org.uk/waveney-songs/","https://visitwaveneyvalley.co.uk/maps/","https://www.suffolkwildlifetrust.org/walor","https://www.broads-authority.gov.uk/boating/navigating-the-broads/water-depths-and-navigation-notes/river-waveney","https://suffolk.camra.org.uk/"]);
waveney.layers.links.view = (function waveney$layers$links$view(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div.useful-links","div.useful-links",-44428765),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"h3","h3",2067611163),"Useful Links"], null),cljs.core.into.cljs$core$IFn$_invoke$arity$2(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"ul","ul",-1349521403)], null),cljs.core.map.cljs$core$IFn$_invoke$arity$2((function (p__21324){
var vec__21325 = p__21324;
var desc = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__21325,(0),null);
var url = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__21325,(1),null);
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"li","li",723558921),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"a","a",-2123407586),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"href","href",-793805698),url], null),desc], null)], null);
}),waveney.layers.links.description__GT_url))], null);
});

//# sourceMappingURL=waveney.layers.links.js.map
